name: Feature request
description: Suggest an idea for this project
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Why should this feature be implemented?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Technical Design Input
      description: |
        (If Applicable) Please describe how you'd like this feature to be implemented or how you'd imagine integrating with it.

        For visual elements, feel free to send us some screenshots/mockups of what it should look like.

  - type: textarea
    attributes:
      label: Additional Content
      description: |
        Anything else we should know?
