on:
  issues:
    types: [opened, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: malmstein/github-asana-action@0.9.0
        with:
          asana-pat: ${{secrets.asana_pat}}
          asana-project: ${{secrets.asana_project_id}}
          action: 'create-asana-issue-task'
